// Package monitoring provides cluster health metrics collection, alerting,
// and visualization for Kubernetes clusters.
package monitoring

import (
	"time"
)

// ClusterMetrics holds aggregated metrics for an entire Kubernetes cluster.
type ClusterMetrics struct {
	Timestamp    time.Time            `json:"timestamp"`
	ClusterName  string               `json:"clusterName"`
	TotalNodes   int                  `json:"totalNodes"`
	ReadyNodes   int                  `json:"readyNodes"`
	TotalPods    int                  `json:"totalPods"`
	RunningPods  int                  `json:"runningPods"`
	PendingPods  int                  `json:"pendingPods"`
	FailedPods   int                  `json:"failedPods"`
	Namespaces   int                  `json:"namespaces"`
	Deployments  int                  `json:"deployments"`
	Services     int                  `json:"services"`
	Nodes        NodeMetricsSummary   `json:"nodes"`
	Pods         PodMetricsSummary    `json:"pods"`
	Resources    ResourceMetrics      `json:"resources"`
	EventMetrics EventMetric          `json:"eventMetrics"`
}

// NodeMetricsSummary holds cluster-wide node statistics.
type NodeMetricsSummary struct {
	Total        int          `json:"total"`
	Ready        int          `json:"ready"`
	NotReady     int          `json:"notReady"`
	Schedulable  int          `json:"schedulable"`
	Unschedulable int         `json:"unschedulable"`
	Details      []NodeDetail `json:"details,omitempty"`
}

// NodeDetail holds per-node metrics.
type NodeDetail struct {
	Name           string            `json:"name"`
	Status         string            `json:"status"`
	Schedulable    bool              `json:"schedulable"`
	CPUCapacity    string            `json:"cpuCapacity"`
	MemoryCapacity string            `json:"memoryCapacity"`
	CPUUsage       string            `json:"cpuUsage"`
	MemoryUsage    string            `json:"memoryUsage"`
	PodCount       int               `json:"podCount"`
	Conditions     map[string]string `json:"conditions,omitempty"`
	Labels         map[string]string `json:"labels,omitempty"`
}

// PodMetricsSummary holds cluster-wide pod statistics.
type PodMetricsSummary struct {
	Total    int         `json:"total"`
	Running  int         `json:"running"`
	Pending  int         `json:"pending"`
	Succeeded int        `json:"succeeded"`
	Failed   int         `json:"failed"`
	Unknown  int         `json:"unknown"`
	Details  []PodDetail `json:"details,omitempty"`
}

// PodDetail holds per-pod metrics.
type PodDetail struct {
	Name      string `json:"name"`
	Namespace string `json:"namespace"`
	Phase     string `json:"phase"`
	Node      string `json:"node"`
	Restarts  int32  `json:"restarts"`
	CPUUsage  string `json:"cpuUsage"`
	MemUsage  string `json:"memUsage"`
}

// ResourceMetrics holds aggregate resource utilization data.
type ResourceMetrics struct {
	CPURequests    string  `json:"cpuRequests"`
	CPULimits      string  `json:"cpuLimits"`
	CPUUsage       string  `json:"cpuUsage"`
	CPUPercent     float64 `json:"cpuPercent"`
	MemoryRequests string  `json:"memoryRequests"`
	MemoryLimits   string  `json:"memoryLimits"`
	MemoryUsage    string  `json:"memoryUsage"`
	MemoryPercent  float64 `json:"memoryPercent"`
}

// EventMetric holds event statistics for the cluster.
type EventMetric struct {
	Total    int `json:"total"`
	Warnings int `json:"warnings"`
	Errors   int `json:"errors"`
	Normal   int `json:"normal"`
	LastHour int `json:"lastHour"`
}

// Alert represents a health alert generated by the monitoring system.
type Alert struct {
	ID         string    `json:"id"`
	Severity   string    `json:"severity"`
	Resource   string    `json:"resource"`
	Message    string    `json:"message"`
	Reason     string    `json:"reason"`
	Timestamp  time.Time `json:"timestamp"`
	Resolved   bool      `json:"resolved"`
	ResolvedAt *time.Time `json:"resolvedAt,omitempty"`
}
